### ISSUE TITLE
Spell check

### ISSUE THREAD

**Issue by brucehohl** [flathub/com.abisource.AbiWord#1]
No dictionaries appear to be included in the flatpak install.  I found this link ( https://www.abisource.com/~fjf/InvisibleAnt/Dictionaries.html ) with dictionaries and Mac instructions but where are the dictionary files placed on a flatpak install?

**Comment by hfiguiere** [comment]
These instruction are not valid for Flatpak.

**Comment by brucehohl** [comment]
Is there a way to get the Abiword spell checker to work in this flatpak install?  
"Tools > Check Spelling" is missing.

Install method on Fedora 28 was:
$ sudo dnf install flatpak
$ sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
$ sudo flatpak install flathub com.abisource.AbiWord
$ flatpak run com.abisource.AbiWord

These dictionary files are available:
$ find /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.30/active/files/share/hunspell/*.dic -type f
/var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.30/active/files/share/hunspell/en_AU.dic
/var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.30/active/files/share/hunspell/en_CA.dic
/var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.30/active/files/share/hunspell/en_GB.dic
/var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.30/active/files/share/hunspell/en_US.dic
/var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.30/active/files/share/hunspell/en_ZA.dic

The Abiword version on Fedora 28 has the cursor bug but spell checker is working.
It would be nice to have both a working cursor and working spell checker!

**Comment by hfiguiere** [comment]
It's definitely missing spellchecking. Looks like enchant is missing.

**Comment by hfiguiere** [comment]
The build with spell checking enabled should be available soon.

Sorry this took this long to be fixed.

**Comment by brucehohl** [comment]
@hfiguiere, many thanks for that fix.
