### ISSUE TITLE
Application closes unexpectedly

### ISSUE THREAD

**Issue by raffaem** [flathub/com.abisource.AbiWord#8]
Sometimes you are working and Abiword just closes.

I'm not alone sine on the software center one comment says:
> The problem? On a Kubuntu system, it is basically impossible to use for more than a few minutes. Becasue it just closes. No errors, no ability to save your work, no warning, nothing. It just closes/

While I'm still not sure how to reproduce it reliably, I see on Flatseal that the application does not have permission to run in the background. 

Maybe that is the reason?

**Comment by hfiguiere** [comment]
> Sometimes you are working and Abiword just closes.

That's called a crash. Unfortunately there are probably a good number of these. AbiWord upstream has been lacking a lot in developers for a few years now.

**Comment by hfiguiere** [comment]
> While I'm still not sure how to reproduce it reliably, I see on Flatseal that the application does not have permission to run in the background.

It doesn't mean what you think it means. It's irrelevant to AbiWord.

**Comment by raffaem** [comment]
Ok, then if it's a crash of AbiWord I guee we can close this issue ..... I also see from their website it gets rarely updated

**Comment by hfiguiere** [comment]
I might release 3.0.5 soon as I fixed a few serious crashes.

**Comment by raffaem** [comment]
Are you a developer of AbiWord too?

I thought you only maintained the flatpak version

**Comment by hfiguiere** [comment]
I'm the last one standing at the moment.
